x-environment-defaults: &environment-defaults
  DEBUG: "False"
  DB_NAME: "django"
  DB_USER: "django_admin"
  DB_PASSWORD: "543678"
  DB_HOST: "postgres"
  DB_PORT: 5432
  SECRET_KEY: "django-insecure-%&o@s)1od6uk*5)l-fliswyxv4xx-mrs)#++&4(que&(q35+y("

networks:
  textgeneration-net:
    driver: bridge

services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    environment:
      POSTGRES_USER: django_admin
      POSTGRES_PASSWORD: 543678
      POSTGRES_DB: django
    ports:
      - "5432:5432"
    networks:
      - textgeneration-net

  textgeneration:
    container_name: django
    build:
      context: ./textgeneration
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      <<: *environment-defaults
    volumes:
      - static_volume:/app/static
    networks:
      - textgeneration-net

  nginx:
    image: nginx:1.27.4
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - textgeneration
    networks:
      - textgeneration-net

  textgeneration-app:
    build:
      context: ./textgeneration-app
    ports:
      - "3000:3000"
    networks:
      - textgeneration-net

volumes:
  static_volume: